name: "Run Tests"

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'tests/**'

  pull_request:
    branches:
      - master
    paths:
      - 'src/**'
      - 'tests/**'
  schedule:
    - cron: '0 0 * * *'


env:
  XDEBUG_MODE: "coverage"
  GITHUB_WORKSPACE: /var/www/html

jobs:
  testing:
    runs-on: ubuntu-latest
    services:
      pgsql:
        image: "postgres:16-alpine" # version of postgres doesn't mater, as Enums are support since forever
        env:
          PGPASSWORD: "laravel_pgenum"
          POSTGRES_DB: "laravel_pgenum"
          POSTGRES_USER: "laravel_pgenum"
          POSTGRES_PASSWORD: "laravel_pgenum"
        ports:
          - '5432:5432'
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: ['8.1', '8.2', '8.3']
        phpts: ['nts', 'ts']
    env:
      extensions: mbstring, xsl, zip, pdo, pdo_pgsql, xdebug, curl
      key: extensions-cache
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Vendor
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-vendor-${{ hashFiles('**/composer.lock') }}

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
          key: ${{ env.key }}

      - name: Cache extensions
        uses: actions/cache@v4
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}-${{ matrix.php-versions }}-${{ matrix.phpts }}
          restore-keys: ${{ steps.extcache.outputs.key }}-${{ matrix.php-versions }}-${{ matrix.phpts }}

      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
          tools: php-cs-fixer, phpcs, composer
          coverage: xdebug
        env:
          phpts: ${{ matrix.phpts }}

      - name: Composer install
        run: composer install -q --no-ansi --prefer-dist --no-interaction --no-progress
        env:
          CACHE_DRIVER: file
          QUEUE_CONNECTION: sync

      - name: Run Tests
        run: vendor/bin/pest --coverage --colors=always --fail-on-risky --fail-on-warning --fail-on-deprecation --strict-coverage
        env:
          DB_HOST: localhost

      - uses: codecov/codecov-action@v4.0.1
        with:
          file: ./.coverage/coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: CodeLieutenant/laravel-pgenum
          name: laravel-pgenum
          fail_ci_if_error: false
